services:
  pokemon-calendar:
    image: delps1001/pokemon-eink-calendar:latest
    container_name: pokemon-calendar
    restart: unless-stopped
    user: "0:0"
    # No privileged needed
    # Map SPI for Waveshare driver; GPIO is via pigpio TCP
    devices:
      - "/dev/spidev0.0:/dev/spidev0.0"
    # Host networking = container can reach pigpio on 127.0.0.1:8888
    network_mode: host

    environment:
      - TZ=America/New_York
      - POKEMON_WEB_HOST=0.0.0.0
      - POKEMON_WEB_PORT=8000
      - POKEMON_DEMO_MODE=false
      # Force gpiozero to use pigpio backend
      - GPIOZERO_PIN_FACTORY=pigpio
      - PIGPIO_ADDR=127.0.0.1
      - PIGPIO_PORT=8888
      # Use the correct Waveshare 7-color “F” driver for your panel:
      - EPD_MODULE=epd7in5f   # or epd5in65f / epd4in01f depending on your exact display

    volumes:
      - pokemon_cache:/app/pokemon_cache
      - pokemon_config:/app/config
      - ./config.json:/app/config.json:ro

    # With host networking, you don't need ports: section
    stop_grace_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    platform: linux/arm/v7
    image: containrrr/watchtower:latest   # multi-arch; safe for 32-bit
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
    command: pokemon-calendar
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  pokemon_cache:
  pokemon_config: