# Pokemon Data with Types and Generations
# Generated from PokeAPI using list endpoints
# This file contains comprehensive type information for Pokemon #1-1025
# This file is auto-generated. Do not edit manually.

POKEMON_DATA = {
    1: {"name": "Bulbasaur", "types": ["grass", "poison"], "generation": 1},
    2: {"name": "Ivysaur", "types": ["grass", "poison"], "generation": 1},
    3: {"name": "Venusaur", "types": ["grass", "poison"], "generation": 1},
    4: {"name": "Charmander", "types": ["fire"], "generation": 1},
    5: {"name": "Charmeleon", "types": ["fire"], "generation": 1},
    6: {"name": "Charizard", "types": ["fire", "flying"], "generation": 1},
    7: {"name": "Squirtle", "types": ["water"], "generation": 1},
    8: {"name": "Wartortle", "types": ["water"], "generation": 1},
    9: {"name": "Blastoise", "types": ["water"], "generation": 1},
    10: {"name": "Caterpie", "types": ["bug"], "generation": 1},
    11: {"name": "Metapod", "types": ["bug"], "generation": 1},
    12: {"name": "Butterfree", "types": ["bug", "flying"], "generation": 1},
    13: {"name": "Weedle", "types": ["bug", "poison"], "generation": 1},
    14: {"name": "Kakuna", "types": ["bug", "poison"], "generation": 1},
    15: {"name": "Beedrill", "types": ["bug", "poison"], "generation": 1},
    16: {"name": "Pidgey", "types": ["normal", "flying"], "generation": 1},
    17: {"name": "Pidgeotto", "types": ["normal", "flying"], "generation": 1},
    18: {"name": "Pidgeot", "types": ["normal", "flying"], "generation": 1},
    19: {"name": "Rattata", "types": ["normal"], "generation": 1},
    20: {"name": "Raticate", "types": ["normal"], "generation": 1},
    21: {"name": "Spearow", "types": ["normal", "flying"], "generation": 1},
    22: {"name": "Fearow", "types": ["normal", "flying"], "generation": 1},
    23: {"name": "Ekans", "types": ["poison"], "generation": 1},
    24: {"name": "Arbok", "types": ["poison"], "generation": 1},
    25: {"name": "Pikachu", "types": ["electric"], "generation": 1},
    26: {"name": "Raichu", "types": ["electric"], "generation": 1},
    27: {"name": "Sandshrew", "types": ["ground"], "generation": 1},
    28: {"name": "Sandslash", "types": ["ground"], "generation": 1},
    29: {"name": "Nidoran♀", "types": ["poison"], "generation": 1},
    30: {"name": "Nidorina", "types": ["poison"], "generation": 1},
    31: {"name": "Nidoqueen", "types": ["poison", "ground"], "generation": 1},
    32: {"name": "Nidoran♂", "types": ["poison"], "generation": 1},
    33: {"name": "Nidorino", "types": ["poison"], "generation": 1},
    34: {"name": "Nidoking", "types": ["poison", "ground"], "generation": 1},
    35: {"name": "Clefairy", "types": ["fairy"], "generation": 1},
    36: {"name": "Clefable", "types": ["fairy"], "generation": 1},
    37: {"name": "Vulpix", "types": ["fire"], "generation": 1},
    38: {"name": "Ninetales", "types": ["fire"], "generation": 1},
    39: {"name": "Jigglypuff", "types": ["normal", "fairy"], "generation": 1},
    40: {"name": "Wigglytuff", "types": ["normal", "fairy"], "generation": 1},
    41: {"name": "Zubat", "types": ["poison", "flying"], "generation": 1},
    42: {"name": "Golbat", "types": ["poison", "flying"], "generation": 1},
    43: {"name": "Oddish", "types": ["grass", "poison"], "generation": 1},
    44: {"name": "Gloom", "types": ["grass", "poison"], "generation": 1},
    45: {"name": "Vileplume", "types": ["grass", "poison"], "generation": 1},
    46: {"name": "Paras", "types": ["bug", "grass"], "generation": 1},
    47: {"name": "Parasect", "types": ["bug", "grass"], "generation": 1},
    48: {"name": "Venonat", "types": ["bug", "poison"], "generation": 1},
    49: {"name": "Venomoth", "types": ["bug", "poison"], "generation": 1},
    50: {"name": "Diglett", "types": ["ground"], "generation": 1},
    51: {"name": "Dugtrio", "types": ["ground"], "generation": 1},
    52: {"name": "Meowth", "types": ["normal"], "generation": 1},
    53: {"name": "Persian", "types": ["normal"], "generation": 1},
    54: {"name": "Psyduck", "types": ["water"], "generation": 1},
    55: {"name": "Golduck", "types": ["water"], "generation": 1},
    56: {"name": "Mankey", "types": ["fighting"], "generation": 1},
    57: {"name": "Primeape", "types": ["fighting"], "generation": 1},
    58: {"name": "Growlithe", "types": ["fire"], "generation": 1},
    59: {"name": "Arcanine", "types": ["fire"], "generation": 1},
    60: {"name": "Poliwag", "types": ["water"], "generation": 1},
    61: {"name": "Poliwhirl", "types": ["water"], "generation": 1},
    62: {"name": "Poliwrath", "types": ["water", "fighting"], "generation": 1},
    63: {"name": "Abra", "types": ["psychic"], "generation": 1},
    64: {"name": "Kadabra", "types": ["psychic"], "generation": 1},
    65: {"name": "Alakazam", "types": ["psychic"], "generation": 1},
    66: {"name": "Machop", "types": ["fighting"], "generation": 1},
    67: {"name": "Machoke", "types": ["fighting"], "generation": 1},
    68: {"name": "Machamp", "types": ["fighting"], "generation": 1},
    69: {"name": "Bellsprout", "types": ["grass", "poison"], "generation": 1},
    70: {"name": "Weepinbell", "types": ["grass", "poison"], "generation": 1},
    71: {"name": "Victreebel", "types": ["grass", "poison"], "generation": 1},
    72: {"name": "Tentacool", "types": ["water", "poison"], "generation": 1},
    73: {"name": "Tentacruel", "types": ["water", "poison"], "generation": 1},
    74: {"name": "Geodude", "types": ["rock", "ground"], "generation": 1},
    75: {"name": "Graveler", "types": ["rock", "ground"], "generation": 1},
    76: {"name": "Golem", "types": ["rock", "ground"], "generation": 1},
    77: {"name": "Ponyta", "types": ["fire"], "generation": 1},
    78: {"name": "Rapidash", "types": ["fire"], "generation": 1},
    79: {"name": "Slowpoke", "types": ["water", "psychic"], "generation": 1},
    80: {"name": "Slowbro", "types": ["water", "psychic"], "generation": 1},
    81: {"name": "Magnemite", "types": ["electric", "steel"], "generation": 1},
    82: {"name": "Magneton", "types": ["electric", "steel"], "generation": 1},
    83: {"name": "Farfetchd", "types": ["normal", "flying"], "generation": 1},
    84: {"name": "Doduo", "types": ["normal", "flying"], "generation": 1},
    85: {"name": "Dodrio", "types": ["normal", "flying"], "generation": 1},
    86: {"name": "Seel", "types": ["water"], "generation": 1},
    87: {"name": "Dewgong", "types": ["water", "ice"], "generation": 1},
    88: {"name": "Grimer", "types": ["poison"], "generation": 1},
    89: {"name": "Muk", "types": ["poison"], "generation": 1},
    90: {"name": "Shellder", "types": ["water"], "generation": 1},
    91: {"name": "Cloyster", "types": ["water", "ice"], "generation": 1},
    92: {"name": "Gastly", "types": ["ghost", "poison"], "generation": 1},
    93: {"name": "Haunter", "types": ["ghost", "poison"], "generation": 1},
    94: {"name": "Gengar", "types": ["ghost", "poison"], "generation": 1},
    95: {"name": "Onix", "types": ["rock", "ground"], "generation": 1},
    96: {"name": "Drowzee", "types": ["psychic"], "generation": 1},
    97: {"name": "Hypno", "types": ["psychic"], "generation": 1},
    98: {"name": "Krabby", "types": ["water"], "generation": 1},
    99: {"name": "Kingler", "types": ["water"], "generation": 1},
    100: {"name": "Voltorb", "types": ["electric"], "generation": 1},
    101: {"name": "Electrode", "types": ["electric"], "generation": 1},
    102: {"name": "Exeggcute", "types": ["grass", "psychic"], "generation": 1},
    103: {"name": "Exeggutor", "types": ["grass", "psychic"], "generation": 1},
    104: {"name": "Cubone", "types": ["ground"], "generation": 1},
    105: {"name": "Marowak", "types": ["ground"], "generation": 1},
    106: {"name": "Hitmonlee", "types": ["fighting"], "generation": 1},
    107: {"name": "Hitmonchan", "types": ["fighting"], "generation": 1},
    108: {"name": "Lickitung", "types": ["normal"], "generation": 1},
    109: {"name": "Koffing", "types": ["poison"], "generation": 1},
    110: {"name": "Weezing", "types": ["poison"], "generation": 1},
    111: {"name": "Rhyhorn", "types": ["ground", "rock"], "generation": 1},
    112: {"name": "Rhydon", "types": ["ground", "rock"], "generation": 1},
    113: {"name": "Chansey", "types": ["normal"], "generation": 1},
    114: {"name": "Tangela", "types": ["grass"], "generation": 1},
    115: {"name": "Kangaskhan", "types": ["normal"], "generation": 1},
    116: {"name": "Horsea", "types": ["water"], "generation": 1},
    117: {"name": "Seadra", "types": ["water"], "generation": 1},
    118: {"name": "Goldeen", "types": ["water"], "generation": 1},
    119: {"name": "Seaking", "types": ["water"], "generation": 1},
    120: {"name": "Staryu", "types": ["water"], "generation": 1},
    121: {"name": "Starmie", "types": ["water", "psychic"], "generation": 1},
    122: {"name": "Mr Mime", "types": ["psychic", "fairy"], "generation": 1},
    123: {"name": "Scyther", "types": ["bug", "flying"], "generation": 1},
    124: {"name": "Jynx", "types": ["ice", "psychic"], "generation": 1},
    125: {"name": "Electabuzz", "types": ["electric"], "generation": 1},
    126: {"name": "Magmar", "types": ["fire"], "generation": 1},
    127: {"name": "Pinsir", "types": ["bug"], "generation": 1},
    128: {"name": "Tauros", "types": ["normal"], "generation": 1},
    129: {"name": "Magikarp", "types": ["water"], "generation": 1},
    130: {"name": "Gyarados", "types": ["water", "flying"], "generation": 1},
    131: {"name": "Lapras", "types": ["water", "ice"], "generation": 1},
    132: {"name": "Ditto", "types": ["normal"], "generation": 1},
    133: {"name": "Eevee", "types": ["normal"], "generation": 1},
    134: {"name": "Vaporeon", "types": ["water"], "generation": 1},
    135: {"name": "Jolteon", "types": ["electric"], "generation": 1},
    136: {"name": "Flareon", "types": ["fire"], "generation": 1},
    137: {"name": "Porygon", "types": ["normal"], "generation": 1},
    138: {"name": "Omanyte", "types": ["rock", "water"], "generation": 1},
    139: {"name": "Omastar", "types": ["rock", "water"], "generation": 1},
    140: {"name": "Kabuto", "types": ["rock", "water"], "generation": 1},
    141: {"name": "Kabutops", "types": ["rock", "water"], "generation": 1},
    142: {"name": "Aerodactyl", "types": ["rock", "flying"], "generation": 1},
    143: {"name": "Snorlax", "types": ["normal"], "generation": 1},
    144: {"name": "Articuno", "types": ["ice", "flying"], "generation": 1},
    145: {"name": "Zapdos", "types": ["electric", "flying"], "generation": 1},
    146: {"name": "Moltres", "types": ["fire", "flying"], "generation": 1},
    147: {"name": "Dratini", "types": ["dragon"], "generation": 1},
    148: {"name": "Dragonair", "types": ["dragon"], "generation": 1},
    149: {"name": "Dragonite", "types": ["dragon", "flying"], "generation": 1},
    150: {"name": "Mewtwo", "types": ["psychic"], "generation": 1},
    151: {"name": "Mew", "types": ["psychic"], "generation": 1},
    152: {"name": "Chikorita", "types": ["grass"], "generation": 2},
    153: {"name": "Bayleef", "types": ["grass"], "generation": 2},
    154: {"name": "Meganium", "types": ["grass"], "generation": 2},
    155: {"name": "Cyndaquil", "types": ["fire"], "generation": 2},
    156: {"name": "Quilava", "types": ["fire"], "generation": 2},
    157: {"name": "Typhlosion", "types": ["fire"], "generation": 2},
    158: {"name": "Totodile", "types": ["water"], "generation": 2},
    159: {"name": "Croconaw", "types": ["water"], "generation": 2},
    160: {"name": "Feraligatr", "types": ["water"], "generation": 2},
    161: {"name": "Sentret", "types": ["normal"], "generation": 2},
    162: {"name": "Furret", "types": ["normal"], "generation": 2},
    163: {"name": "Hoothoot", "types": ["normal", "flying"], "generation": 2},
    164: {"name": "Noctowl", "types": ["normal", "flying"], "generation": 2},
    165: {"name": "Ledyba", "types": ["bug", "flying"], "generation": 2},
    166: {"name": "Ledian", "types": ["bug", "flying"], "generation": 2},
    167: {"name": "Spinarak", "types": ["bug", "poison"], "generation": 2},
    168: {"name": "Ariados", "types": ["bug", "poison"], "generation": 2},
    169: {"name": "Crobat", "types": ["poison", "flying"], "generation": 2},
    170: {"name": "Chinchou", "types": ["water", "electric"], "generation": 2},
    171: {"name": "Lanturn", "types": ["water", "electric"], "generation": 2},
    172: {"name": "Pichu", "types": ["electric"], "generation": 2},
    173: {"name": "Cleffa", "types": ["fairy"], "generation": 2},
    174: {"name": "Igglybuff", "types": ["normal", "fairy"], "generation": 2},
    175: {"name": "Togepi", "types": ["fairy"], "generation": 2},
    176: {"name": "Togetic", "types": ["fairy", "flying"], "generation": 2},
    177: {"name": "Natu", "types": ["psychic", "flying"], "generation": 2},
    178: {"name": "Xatu", "types": ["psychic", "flying"], "generation": 2},
    179: {"name": "Mareep", "types": ["electric"], "generation": 2},
    180: {"name": "Flaaffy", "types": ["electric"], "generation": 2},
    181: {"name": "Ampharos", "types": ["electric"], "generation": 2},
    182: {"name": "Bellossom", "types": ["grass"], "generation": 2},
    183: {"name": "Marill", "types": ["water", "fairy"], "generation": 2},
    184: {"name": "Azumarill", "types": ["water", "fairy"], "generation": 2},
    185: {"name": "Sudowoodo", "types": ["rock"], "generation": 2},
    186: {"name": "Politoed", "types": ["water"], "generation": 2},
    187: {"name": "Hoppip", "types": ["grass", "flying"], "generation": 2},
    188: {"name": "Skiploom", "types": ["grass", "flying"], "generation": 2},
    189: {"name": "Jumpluff", "types": ["grass", "flying"], "generation": 2},
    190: {"name": "Aipom", "types": ["normal"], "generation": 2},
    191: {"name": "Sunkern", "types": ["grass"], "generation": 2},
    192: {"name": "Sunflora", "types": ["grass"], "generation": 2},
    193: {"name": "Yanma", "types": ["bug", "flying"], "generation": 2},
    194: {"name": "Wooper", "types": ["water", "ground"], "generation": 2},
    195: {"name": "Quagsire", "types": ["water", "ground"], "generation": 2},
    196: {"name": "Espeon", "types": ["psychic"], "generation": 2},
    197: {"name": "Umbreon", "types": ["dark"], "generation": 2},
    198: {"name": "Murkrow", "types": ["dark", "flying"], "generation": 2},
    199: {"name": "Slowking", "types": ["water", "psychic"], "generation": 2},
    200: {"name": "Misdreavus", "types": ["ghost"], "generation": 2},
    201: {"name": "Unown", "types": ["psychic"], "generation": 2},
    202: {"name": "Wobbuffet", "types": ["psychic"], "generation": 2},
    203: {"name": "Girafarig", "types": ["normal", "psychic"], "generation": 2},
    204: {"name": "Pineco", "types": ["bug"], "generation": 2},
    205: {"name": "Forretress", "types": ["bug", "steel"], "generation": 2},
    206: {"name": "Dunsparce", "types": ["normal"], "generation": 2},
    207: {"name": "Gligar", "types": ["ground", "flying"], "generation": 2},
    208: {"name": "Steelix", "types": ["steel", "ground"], "generation": 2},
    209: {"name": "Snubbull", "types": ["fairy"], "generation": 2},
    210: {"name": "Granbull", "types": ["fairy"], "generation": 2},
    211: {"name": "Qwilfish", "types": ["water", "poison"], "generation": 2},
    212: {"name": "Scizor", "types": ["bug", "steel"], "generation": 2},
    213: {"name": "Shuckle", "types": ["bug", "rock"], "generation": 2},
    214: {"name": "Heracross", "types": ["bug", "fighting"], "generation": 2},
    215: {"name": "Sneasel", "types": ["dark", "ice"], "generation": 2},
    216: {"name": "Teddiursa", "types": ["normal"], "generation": 2},
    217: {"name": "Ursaring", "types": ["normal"], "generation": 2},
    218: {"name": "Slugma", "types": ["fire"], "generation": 2},
    219: {"name": "Magcargo", "types": ["fire", "rock"], "generation": 2},
    220: {"name": "Swinub", "types": ["ice", "ground"], "generation": 2},
    221: {"name": "Piloswine", "types": ["ice", "ground"], "generation": 2},
    222: {"name": "Corsola", "types": ["water", "rock"], "generation": 2},
    223: {"name": "Remoraid", "types": ["water"], "generation": 2},
    224: {"name": "Octillery", "types": ["water"], "generation": 2},
    225: {"name": "Delibird", "types": ["ice", "flying"], "generation": 2},
    226: {"name": "Mantine", "types": ["water", "flying"], "generation": 2},
    227: {"name": "Skarmory", "types": ["steel", "flying"], "generation": 2},
    228: {"name": "Houndour", "types": ["dark", "fire"], "generation": 2},
    229: {"name": "Houndoom", "types": ["dark", "fire"], "generation": 2},
    230: {"name": "Kingdra", "types": ["water", "dragon"], "generation": 2},
    231: {"name": "Phanpy", "types": ["ground"], "generation": 2},
    232: {"name": "Donphan", "types": ["ground"], "generation": 2},
    233: {"name": "Porygon2", "types": ["normal"], "generation": 2},
    234: {"name": "Stantler", "types": ["normal"], "generation": 2},
    235: {"name": "Smeargle", "types": ["normal"], "generation": 2},
    236: {"name": "Tyrogue", "types": ["fighting"], "generation": 2},
    237: {"name": "Hitmontop", "types": ["fighting"], "generation": 2},
    238: {"name": "Smoochum", "types": ["ice", "psychic"], "generation": 2},
    239: {"name": "Elekid", "types": ["electric"], "generation": 2},
    240: {"name": "Magby", "types": ["fire"], "generation": 2},
    241: {"name": "Miltank", "types": ["normal"], "generation": 2},
    242: {"name": "Blissey", "types": ["normal"], "generation": 2},
    243: {"name": "Raikou", "types": ["electric"], "generation": 2},
    244: {"name": "Entei", "types": ["fire"], "generation": 2},
    245: {"name": "Suicune", "types": ["water"], "generation": 2},
    246: {"name": "Larvitar", "types": ["rock", "ground"], "generation": 2},
    247: {"name": "Pupitar", "types": ["rock", "ground"], "generation": 2},
    248: {"name": "Tyranitar", "types": ["rock", "dark"], "generation": 2},
    249: {"name": "Lugia", "types": ["psychic", "flying"], "generation": 2},
    250: {"name": "Ho Oh", "types": ["fire", "flying"], "generation": 2},
    251: {"name": "Celebi", "types": ["psychic", "grass"], "generation": 2},
    252: {"name": "Treecko", "types": ["grass"], "generation": 3},
    253: {"name": "Grovyle", "types": ["grass"], "generation": 3},
    254: {"name": "Sceptile", "types": ["grass"], "generation": 3},
    255: {"name": "Torchic", "types": ["fire"], "generation": 3},
    256: {"name": "Combusken", "types": ["fire", "fighting"], "generation": 3},
    257: {"name": "Blaziken", "types": ["fire", "fighting"], "generation": 3},
    258: {"name": "Mudkip", "types": ["water"], "generation": 3},
    259: {"name": "Marshtomp", "types": ["water", "ground"], "generation": 3},
    260: {"name": "Swampert", "types": ["water", "ground"], "generation": 3},
    261: {"name": "Poochyena", "types": ["dark"], "generation": 3},
    262: {"name": "Mightyena", "types": ["dark"], "generation": 3},
    263: {"name": "Zigzagoon", "types": ["normal"], "generation": 3},
    264: {"name": "Linoone", "types": ["normal"], "generation": 3},
    265: {"name": "Wurmple", "types": ["bug"], "generation": 3},
    266: {"name": "Silcoon", "types": ["bug"], "generation": 3},
    267: {"name": "Beautifly", "types": ["bug", "flying"], "generation": 3},
    268: {"name": "Cascoon", "types": ["bug"], "generation": 3},
    269: {"name": "Dustox", "types": ["bug", "poison"], "generation": 3},
    270: {"name": "Lotad", "types": ["water", "grass"], "generation": 3},
    271: {"name": "Lombre", "types": ["water", "grass"], "generation": 3},
    272: {"name": "Ludicolo", "types": ["water", "grass"], "generation": 3},
    273: {"name": "Seedot", "types": ["grass"], "generation": 3},
    274: {"name": "Nuzleaf", "types": ["grass", "dark"], "generation": 3},
    275: {"name": "Shiftry", "types": ["grass", "dark"], "generation": 3},
    276: {"name": "Taillow", "types": ["normal", "flying"], "generation": 3},
    277: {"name": "Swellow", "types": ["normal", "flying"], "generation": 3},
    278: {"name": "Wingull", "types": ["water", "flying"], "generation": 3},
    279: {"name": "Pelipper", "types": ["water", "flying"], "generation": 3},
    280: {"name": "Ralts", "types": ["psychic", "fairy"], "generation": 3},
    281: {"name": "Kirlia", "types": ["psychic", "fairy"], "generation": 3},
    282: {"name": "Gardevoir", "types": ["psychic", "fairy"], "generation": 3},
    283: {"name": "Surskit", "types": ["bug", "water"], "generation": 3},
    284: {"name": "Masquerain", "types": ["bug", "flying"], "generation": 3},
    285: {"name": "Shroomish", "types": ["grass"], "generation": 3},
    286: {"name": "Breloom", "types": ["grass", "fighting"], "generation": 3},
    287: {"name": "Slakoth", "types": ["normal"], "generation": 3},
    288: {"name": "Vigoroth", "types": ["normal"], "generation": 3},
    289: {"name": "Slaking", "types": ["normal"], "generation": 3},
    290: {"name": "Nincada", "types": ["bug", "ground"], "generation": 3},
    291: {"name": "Ninjask", "types": ["bug", "flying"], "generation": 3},
    292: {"name": "Shedinja", "types": ["bug", "ghost"], "generation": 3},
    293: {"name": "Whismur", "types": ["normal"], "generation": 3},
    294: {"name": "Loudred", "types": ["normal"], "generation": 3},
    295: {"name": "Exploud", "types": ["normal"], "generation": 3},
    296: {"name": "Makuhita", "types": ["fighting"], "generation": 3},
    297: {"name": "Hariyama", "types": ["fighting"], "generation": 3},
    298: {"name": "Azurill", "types": ["normal", "fairy"], "generation": 3},
    299: {"name": "Nosepass", "types": ["rock"], "generation": 3},
    300: {"name": "Skitty", "types": ["normal"], "generation": 3},
    301: {"name": "Delcatty", "types": ["normal"], "generation": 3},
    302: {"name": "Sableye", "types": ["dark", "ghost"], "generation": 3},
    303: {"name": "Mawile", "types": ["steel", "fairy"], "generation": 3},
    304: {"name": "Aron", "types": ["steel", "rock"], "generation": 3},
    305: {"name": "Lairon", "types": ["steel", "rock"], "generation": 3},
    306: {"name": "Aggron", "types": ["steel", "rock"], "generation": 3},
    307: {"name": "Meditite", "types": ["fighting", "psychic"], "generation": 3},
    308: {"name": "Medicham", "types": ["fighting", "psychic"], "generation": 3},
    309: {"name": "Electrike", "types": ["electric"], "generation": 3},
    310: {"name": "Manectric", "types": ["electric"], "generation": 3},
    311: {"name": "Plusle", "types": ["electric"], "generation": 3},
    312: {"name": "Minun", "types": ["electric"], "generation": 3},
    313: {"name": "Volbeat", "types": ["bug"], "generation": 3},
    314: {"name": "Illumise", "types": ["bug"], "generation": 3},
    315: {"name": "Roselia", "types": ["grass", "poison"], "generation": 3},
    316: {"name": "Gulpin", "types": ["poison"], "generation": 3},
    317: {"name": "Swalot", "types": ["poison"], "generation": 3},
    318: {"name": "Carvanha", "types": ["water", "dark"], "generation": 3},
    319: {"name": "Sharpedo", "types": ["water", "dark"], "generation": 3},
    320: {"name": "Wailmer", "types": ["water"], "generation": 3},
    321: {"name": "Wailord", "types": ["water"], "generation": 3},
    322: {"name": "Numel", "types": ["fire", "ground"], "generation": 3},
    323: {"name": "Camerupt", "types": ["fire", "ground"], "generation": 3},
    324: {"name": "Torkoal", "types": ["fire"], "generation": 3},
    325: {"name": "Spoink", "types": ["psychic"], "generation": 3},
    326: {"name": "Grumpig", "types": ["psychic"], "generation": 3},
    327: {"name": "Spinda", "types": ["normal"], "generation": 3},
    328: {"name": "Trapinch", "types": ["ground"], "generation": 3},
    329: {"name": "Vibrava", "types": ["ground", "dragon"], "generation": 3},
    330: {"name": "Flygon", "types": ["ground", "dragon"], "generation": 3},
    331: {"name": "Cacnea", "types": ["grass"], "generation": 3},
    332: {"name": "Cacturne", "types": ["grass", "dark"], "generation": 3},
    333: {"name": "Swablu", "types": ["normal", "flying"], "generation": 3},
    334: {"name": "Altaria", "types": ["dragon", "flying"], "generation": 3},
    335: {"name": "Zangoose", "types": ["normal"], "generation": 3},
    336: {"name": "Seviper", "types": ["poison"], "generation": 3},
    337: {"name": "Lunatone", "types": ["rock", "psychic"], "generation": 3},
    338: {"name": "Solrock", "types": ["rock", "psychic"], "generation": 3},
    339: {"name": "Barboach", "types": ["water", "ground"], "generation": 3},
    340: {"name": "Whiscash", "types": ["water", "ground"], "generation": 3},
    341: {"name": "Corphish", "types": ["water"], "generation": 3},
    342: {"name": "Crawdaunt", "types": ["water", "dark"], "generation": 3},
    343: {"name": "Baltoy", "types": ["ground", "psychic"], "generation": 3},
    344: {"name": "Claydol", "types": ["ground", "psychic"], "generation": 3},
    345: {"name": "Lileep", "types": ["rock", "grass"], "generation": 3},
    346: {"name": "Cradily", "types": ["rock", "grass"], "generation": 3},
    347: {"name": "Anorith", "types": ["rock", "bug"], "generation": 3},
    348: {"name": "Armaldo", "types": ["rock", "bug"], "generation": 3},
    349: {"name": "Feebas", "types": ["water"], "generation": 3},
    350: {"name": "Milotic", "types": ["water"], "generation": 3},
    351: {"name": "Castform", "types": ["normal"], "generation": 3},
    352: {"name": "Kecleon", "types": ["normal"], "generation": 3},
    353: {"name": "Shuppet", "types": ["ghost"], "generation": 3},
    354: {"name": "Banette", "types": ["ghost"], "generation": 3},
    355: {"name": "Duskull", "types": ["ghost"], "generation": 3},
    356: {"name": "Dusclops", "types": ["ghost"], "generation": 3},
    357: {"name": "Tropius", "types": ["grass", "flying"], "generation": 3},
    358: {"name": "Chimecho", "types": ["psychic"], "generation": 3},
    359: {"name": "Absol", "types": ["dark"], "generation": 3},
    360: {"name": "Wynaut", "types": ["psychic"], "generation": 3},
    361: {"name": "Snorunt", "types": ["ice"], "generation": 3},
    362: {"name": "Glalie", "types": ["ice"], "generation": 3},
    363: {"name": "Spheal", "types": ["ice", "water"], "generation": 3},
    364: {"name": "Sealeo", "types": ["ice", "water"], "generation": 3},
    365: {"name": "Walrein", "types": ["ice", "water"], "generation": 3},
    366: {"name": "Clamperl", "types": ["water"], "generation": 3},
    367: {"name": "Huntail", "types": ["water"], "generation": 3},
    368: {"name": "Gorebyss", "types": ["water"], "generation": 3},
    369: {"name": "Relicanth", "types": ["water", "rock"], "generation": 3},
    370: {"name": "Luvdisc", "types": ["water"], "generation": 3},
    371: {"name": "Bagon", "types": ["dragon"], "generation": 3},
    372: {"name": "Shelgon", "types": ["dragon"], "generation": 3},
    373: {"name": "Salamence", "types": ["dragon", "flying"], "generation": 3},
    374: {"name": "Beldum", "types": ["steel", "psychic"], "generation": 3},
    375: {"name": "Metang", "types": ["steel", "psychic"], "generation": 3},
    376: {"name": "Metagross", "types": ["steel", "psychic"], "generation": 3},
    377: {"name": "Regirock", "types": ["rock"], "generation": 3},
    378: {"name": "Regice", "types": ["ice"], "generation": 3},
    379: {"name": "Registeel", "types": ["steel"], "generation": 3},
    380: {"name": "Latias", "types": ["dragon", "psychic"], "generation": 3},
    381: {"name": "Latios", "types": ["dragon", "psychic"], "generation": 3},
    382: {"name": "Kyogre", "types": ["water"], "generation": 3},
    383: {"name": "Groudon", "types": ["ground"], "generation": 3},
    384: {"name": "Rayquaza", "types": ["dragon", "flying"], "generation": 3},
    385: {"name": "Jirachi", "types": ["steel", "psychic"], "generation": 3},
    386: {"name": "Deoxys Normal", "types": ["psychic"], "generation": 3},
    387: {"name": "Turtwig", "types": ["grass"], "generation": 4},
    388: {"name": "Grotle", "types": ["grass"], "generation": 4},
    389: {"name": "Torterra", "types": ["grass", "ground"], "generation": 4},
    390: {"name": "Chimchar", "types": ["fire"], "generation": 4},
    391: {"name": "Monferno", "types": ["fire", "fighting"], "generation": 4},
    392: {"name": "Infernape", "types": ["fire", "fighting"], "generation": 4},
    393: {"name": "Piplup", "types": ["water"], "generation": 4},
    394: {"name": "Prinplup", "types": ["water"], "generation": 4},
    395: {"name": "Empoleon", "types": ["water", "steel"], "generation": 4},
    396: {"name": "Starly", "types": ["normal", "flying"], "generation": 4},
    397: {"name": "Staravia", "types": ["normal", "flying"], "generation": 4},
    398: {"name": "Staraptor", "types": ["normal", "flying"], "generation": 4},
    399: {"name": "Bidoof", "types": ["normal"], "generation": 4},
    400: {"name": "Bibarel", "types": ["normal", "water"], "generation": 4},
    401: {"name": "Kricketot", "types": ["bug"], "generation": 4},
    402: {"name": "Kricketune", "types": ["bug"], "generation": 4},
    403: {"name": "Shinx", "types": ["electric"], "generation": 4},
    404: {"name": "Luxio", "types": ["electric"], "generation": 4},
    405: {"name": "Luxray", "types": ["electric"], "generation": 4},
    406: {"name": "Budew", "types": ["grass", "poison"], "generation": 4},
    407: {"name": "Roserade", "types": ["grass", "poison"], "generation": 4},
    408: {"name": "Cranidos", "types": ["rock"], "generation": 4},
    409: {"name": "Rampardos", "types": ["rock"], "generation": 4},
    410: {"name": "Shieldon", "types": ["rock", "steel"], "generation": 4},
    411: {"name": "Bastiodon", "types": ["rock", "steel"], "generation": 4},
    412: {"name": "Burmy", "types": ["bug"], "generation": 4},
    413: {"name": "Wormadam Plant", "types": ["bug", "grass"], "generation": 4},
    414: {"name": "Mothim", "types": ["bug", "flying"], "generation": 4},
    415: {"name": "Combee", "types": ["bug", "flying"], "generation": 4},
    416: {"name": "Vespiquen", "types": ["bug", "flying"], "generation": 4},
    417: {"name": "Pachirisu", "types": ["electric"], "generation": 4},
    418: {"name": "Buizel", "types": ["water"], "generation": 4},
    419: {"name": "Floatzel", "types": ["water"], "generation": 4},
    420: {"name": "Cherubi", "types": ["grass"], "generation": 4},
    421: {"name": "Cherrim", "types": ["grass"], "generation": 4},
    422: {"name": "Shellos", "types": ["water"], "generation": 4},
    423: {"name": "Gastrodon", "types": ["water", "ground"], "generation": 4},
    424: {"name": "Ambipom", "types": ["normal"], "generation": 4},
    425: {"name": "Drifloon", "types": ["ghost", "flying"], "generation": 4},
    426: {"name": "Drifblim", "types": ["ghost", "flying"], "generation": 4},
    427: {"name": "Buneary", "types": ["normal"], "generation": 4},
    428: {"name": "Lopunny", "types": ["normal"], "generation": 4},
    429: {"name": "Mismagius", "types": ["ghost"], "generation": 4},
    430: {"name": "Honchkrow", "types": ["dark", "flying"], "generation": 4},
    431: {"name": "Glameow", "types": ["normal"], "generation": 4},
    432: {"name": "Purugly", "types": ["normal"], "generation": 4},
    433: {"name": "Chingling", "types": ["psychic"], "generation": 4},
    434: {"name": "Stunky", "types": ["poison", "dark"], "generation": 4},
    435: {"name": "Skuntank", "types": ["poison", "dark"], "generation": 4},
    436: {"name": "Bronzor", "types": ["steel", "psychic"], "generation": 4},
    437: {"name": "Bronzong", "types": ["steel", "psychic"], "generation": 4},
    438: {"name": "Bonsly", "types": ["rock"], "generation": 4},
    439: {"name": "Mime Jr", "types": ["psychic", "fairy"], "generation": 4},
    440: {"name": "Happiny", "types": ["normal"], "generation": 4},
    441: {"name": "Chatot", "types": ["normal", "flying"], "generation": 4},
    442: {"name": "Spiritomb", "types": ["ghost", "dark"], "generation": 4},
    443: {"name": "Gible", "types": ["dragon", "ground"], "generation": 4},
    444: {"name": "Gabite", "types": ["dragon", "ground"], "generation": 4},
    445: {"name": "Garchomp", "types": ["dragon", "ground"], "generation": 4},
    446: {"name": "Munchlax", "types": ["normal"], "generation": 4},
    447: {"name": "Riolu", "types": ["fighting"], "generation": 4},
    448: {"name": "Lucario", "types": ["fighting", "steel"], "generation": 4},
    449: {"name": "Hippopotas", "types": ["ground"], "generation": 4},
    450: {"name": "Hippowdon", "types": ["ground"], "generation": 4},
    451: {"name": "Skorupi", "types": ["poison", "bug"], "generation": 4},
    452: {"name": "Drapion", "types": ["poison", "dark"], "generation": 4},
    453: {"name": "Croagunk", "types": ["poison", "fighting"], "generation": 4},
    454: {"name": "Toxicroak", "types": ["poison", "fighting"], "generation": 4},
    455: {"name": "Carnivine", "types": ["grass"], "generation": 4},
    456: {"name": "Finneon", "types": ["water"], "generation": 4},
    457: {"name": "Lumineon", "types": ["water"], "generation": 4},
    458: {"name": "Mantyke", "types": ["water", "flying"], "generation": 4},
    459: {"name": "Snover", "types": ["grass", "ice"], "generation": 4},
    460: {"name": "Abomasnow", "types": ["grass", "ice"], "generation": 4},
    461: {"name": "Weavile", "types": ["dark", "ice"], "generation": 4},
    462: {"name": "Magnezone", "types": ["electric", "steel"], "generation": 4},
    463: {"name": "Lickilicky", "types": ["normal"], "generation": 4},
    464: {"name": "Rhyperior", "types": ["ground", "rock"], "generation": 4},
    465: {"name": "Tangrowth", "types": ["grass"], "generation": 4},
    466: {"name": "Electivire", "types": ["electric"], "generation": 4},
    467: {"name": "Magmortar", "types": ["fire"], "generation": 4},
    468: {"name": "Togekiss", "types": ["fairy", "flying"], "generation": 4},
    469: {"name": "Yanmega", "types": ["bug", "flying"], "generation": 4},
    470: {"name": "Leafeon", "types": ["grass"], "generation": 4},
    471: {"name": "Glaceon", "types": ["ice"], "generation": 4},
    472: {"name": "Gliscor", "types": ["ground", "flying"], "generation": 4},
    473: {"name": "Mamoswine", "types": ["ice", "ground"], "generation": 4},
    474: {"name": "Porygon Z", "types": ["normal"], "generation": 4},
    475: {"name": "Gallade", "types": ["psychic", "fighting"], "generation": 4},
    476: {"name": "Probopass", "types": ["rock", "steel"], "generation": 4},
    477: {"name": "Dusknoir", "types": ["ghost"], "generation": 4},
    478: {"name": "Froslass", "types": ["ice", "ghost"], "generation": 4},
    479: {"name": "Rotom", "types": ["electric", "ghost"], "generation": 4},
    480: {"name": "Uxie", "types": ["psychic"], "generation": 4},
    481: {"name": "Mesprit", "types": ["psychic"], "generation": 4},
    482: {"name": "Azelf", "types": ["psychic"], "generation": 4},
    483: {"name": "Dialga", "types": ["steel", "dragon"], "generation": 4},
    484: {"name": "Palkia", "types": ["water", "dragon"], "generation": 4},
    485: {"name": "Heatran", "types": ["fire", "steel"], "generation": 4},
    486: {"name": "Regigigas", "types": ["normal"], "generation": 4},
    487: {"name": "Giratina Altered", "types": ["ghost", "dragon"], "generation": 4},
    488: {"name": "Cresselia", "types": ["psychic"], "generation": 4},
    489: {"name": "Phione", "types": ["water"], "generation": 4},
    490: {"name": "Manaphy", "types": ["water"], "generation": 4},
    491: {"name": "Darkrai", "types": ["dark"], "generation": 4},
    492: {"name": "Shaymin Land", "types": ["grass"], "generation": 4},
    493: {"name": "Arceus", "types": ["normal"], "generation": 4},
    494: {"name": "Victini", "types": ["psychic", "fire"], "generation": 5},
    495: {"name": "Snivy", "types": ["grass"], "generation": 5},
    496: {"name": "Servine", "types": ["grass"], "generation": 5},
    497: {"name": "Serperior", "types": ["grass"], "generation": 5},
    498: {"name": "Tepig", "types": ["fire"], "generation": 5},
    499: {"name": "Pignite", "types": ["fire", "fighting"], "generation": 5},
    500: {"name": "Emboar", "types": ["fire", "fighting"], "generation": 5},
    501: {"name": "Oshawott", "types": ["water"], "generation": 5},
    502: {"name": "Dewott", "types": ["water"], "generation": 5},
    503: {"name": "Samurott", "types": ["water"], "generation": 5},
    504: {"name": "Patrat", "types": ["normal"], "generation": 5},
    505: {"name": "Watchog", "types": ["normal"], "generation": 5},
    506: {"name": "Lillipup", "types": ["normal"], "generation": 5},
    507: {"name": "Herdier", "types": ["normal"], "generation": 5},
    508: {"name": "Stoutland", "types": ["normal"], "generation": 5},
    509: {"name": "Purrloin", "types": ["dark"], "generation": 5},
    510: {"name": "Liepard", "types": ["dark"], "generation": 5},
    511: {"name": "Pansage", "types": ["grass"], "generation": 5},
    512: {"name": "Simisage", "types": ["grass"], "generation": 5},
    513: {"name": "Pansear", "types": ["fire"], "generation": 5},
    514: {"name": "Simisear", "types": ["fire"], "generation": 5},
    515: {"name": "Panpour", "types": ["water"], "generation": 5},
    516: {"name": "Simipour", "types": ["water"], "generation": 5},
    517: {"name": "Munna", "types": ["psychic"], "generation": 5},
    518: {"name": "Musharna", "types": ["psychic"], "generation": 5},
    519: {"name": "Pidove", "types": ["normal", "flying"], "generation": 5},
    520: {"name": "Tranquill", "types": ["normal", "flying"], "generation": 5},
    521: {"name": "Unfezant", "types": ["normal", "flying"], "generation": 5},
    522: {"name": "Blitzle", "types": ["electric"], "generation": 5},
    523: {"name": "Zebstrika", "types": ["electric"], "generation": 5},
    524: {"name": "Roggenrola", "types": ["rock"], "generation": 5},
    525: {"name": "Boldore", "types": ["rock"], "generation": 5},
    526: {"name": "Gigalith", "types": ["rock"], "generation": 5},
    527: {"name": "Woobat", "types": ["psychic", "flying"], "generation": 5},
    528: {"name": "Swoobat", "types": ["psychic", "flying"], "generation": 5},
    529: {"name": "Drilbur", "types": ["ground"], "generation": 5},
    530: {"name": "Excadrill", "types": ["ground", "steel"], "generation": 5},
    531: {"name": "Audino", "types": ["normal"], "generation": 5},
    532: {"name": "Timburr", "types": ["fighting"], "generation": 5},
    533: {"name": "Gurdurr", "types": ["fighting"], "generation": 5},
    534: {"name": "Conkeldurr", "types": ["fighting"], "generation": 5},
    535: {"name": "Tympole", "types": ["water"], "generation": 5},
    536: {"name": "Palpitoad", "types": ["water", "ground"], "generation": 5},
    537: {"name": "Seismitoad", "types": ["water", "ground"], "generation": 5},
    538: {"name": "Throh", "types": ["fighting"], "generation": 5},
    539: {"name": "Sawk", "types": ["fighting"], "generation": 5},
    540: {"name": "Sewaddle", "types": ["bug", "grass"], "generation": 5},
    541: {"name": "Swadloon", "types": ["bug", "grass"], "generation": 5},
    542: {"name": "Leavanny", "types": ["bug", "grass"], "generation": 5},
    543: {"name": "Venipede", "types": ["bug", "poison"], "generation": 5},
    544: {"name": "Whirlipede", "types": ["bug", "poison"], "generation": 5},
    545: {"name": "Scolipede", "types": ["bug", "poison"], "generation": 5},
    546: {"name": "Cottonee", "types": ["grass", "fairy"], "generation": 5},
    547: {"name": "Whimsicott", "types": ["grass", "fairy"], "generation": 5},
    548: {"name": "Petilil", "types": ["grass"], "generation": 5},
    549: {"name": "Lilligant", "types": ["grass"], "generation": 5},
    550: {"name": "Basculin Red Striped", "types": ["water"], "generation": 5},
    551: {"name": "Sandile", "types": ["ground", "dark"], "generation": 5},
    552: {"name": "Krokorok", "types": ["ground", "dark"], "generation": 5},
    553: {"name": "Krookodile", "types": ["ground", "dark"], "generation": 5},
    554: {"name": "Darumaka", "types": ["fire"], "generation": 5},
    555: {"name": "Darmanitan Standard", "types": ["fire"], "generation": 5},
    556: {"name": "Maractus", "types": ["grass"], "generation": 5},
    557: {"name": "Dwebble", "types": ["bug", "rock"], "generation": 5},
    558: {"name": "Crustle", "types": ["bug", "rock"], "generation": 5},
    559: {"name": "Scraggy", "types": ["dark", "fighting"], "generation": 5},
    560: {"name": "Scrafty", "types": ["dark", "fighting"], "generation": 5},
    561: {"name": "Sigilyph", "types": ["psychic", "flying"], "generation": 5},
    562: {"name": "Yamask", "types": ["ghost"], "generation": 5},
    563: {"name": "Cofagrigus", "types": ["ghost"], "generation": 5},
    564: {"name": "Tirtouga", "types": ["water", "rock"], "generation": 5},
    565: {"name": "Carracosta", "types": ["water", "rock"], "generation": 5},
    566: {"name": "Archen", "types": ["rock", "flying"], "generation": 5},
    567: {"name": "Archeops", "types": ["rock", "flying"], "generation": 5},
    568: {"name": "Trubbish", "types": ["poison"], "generation": 5},
    569: {"name": "Garbodor", "types": ["poison"], "generation": 5},
    570: {"name": "Zorua", "types": ["dark"], "generation": 5},
    571: {"name": "Zoroark", "types": ["dark"], "generation": 5},
    572: {"name": "Minccino", "types": ["normal"], "generation": 5},
    573: {"name": "Cinccino", "types": ["normal"], "generation": 5},
    574: {"name": "Gothita", "types": ["psychic"], "generation": 5},
    575: {"name": "Gothorita", "types": ["psychic"], "generation": 5},
    576: {"name": "Gothitelle", "types": ["psychic"], "generation": 5},
    577: {"name": "Solosis", "types": ["psychic"], "generation": 5},
    578: {"name": "Duosion", "types": ["psychic"], "generation": 5},
    579: {"name": "Reuniclus", "types": ["psychic"], "generation": 5},
    580: {"name": "Ducklett", "types": ["water", "flying"], "generation": 5},
    581: {"name": "Swanna", "types": ["water", "flying"], "generation": 5},
    582: {"name": "Vanillite", "types": ["ice"], "generation": 5},
    583: {"name": "Vanillish", "types": ["ice"], "generation": 5},
    584: {"name": "Vanilluxe", "types": ["ice"], "generation": 5},
    585: {"name": "Deerling", "types": ["normal", "grass"], "generation": 5},
    586: {"name": "Sawsbuck", "types": ["normal", "grass"], "generation": 5},
    587: {"name": "Emolga", "types": ["electric", "flying"], "generation": 5},
    588: {"name": "Karrablast", "types": ["bug"], "generation": 5},
    589: {"name": "Escavalier", "types": ["bug", "steel"], "generation": 5},
    590: {"name": "Foongus", "types": ["grass", "poison"], "generation": 5},
    591: {"name": "Amoonguss", "types": ["grass", "poison"], "generation": 5},
    592: {"name": "Frillish", "types": ["water", "ghost"], "generation": 5},
    593: {"name": "Jellicent", "types": ["water", "ghost"], "generation": 5},
    594: {"name": "Alomomola", "types": ["water"], "generation": 5},
    595: {"name": "Joltik", "types": ["bug", "electric"], "generation": 5},
    596: {"name": "Galvantula", "types": ["bug", "electric"], "generation": 5},
    597: {"name": "Ferroseed", "types": ["grass", "steel"], "generation": 5},
    598: {"name": "Ferrothorn", "types": ["grass", "steel"], "generation": 5},
    599: {"name": "Klink", "types": ["steel"], "generation": 5},
    600: {"name": "Klang", "types": ["steel"], "generation": 5},
    601: {"name": "Klinklang", "types": ["steel"], "generation": 5},
    602: {"name": "Tynamo", "types": ["electric"], "generation": 5},
    603: {"name": "Eelektrik", "types": ["electric"], "generation": 5},
    604: {"name": "Eelektross", "types": ["electric"], "generation": 5},
    605: {"name": "Elgyem", "types": ["psychic"], "generation": 5},
    606: {"name": "Beheeyem", "types": ["psychic"], "generation": 5},
    607: {"name": "Litwick", "types": ["ghost", "fire"], "generation": 5},
    608: {"name": "Lampent", "types": ["ghost", "fire"], "generation": 5},
    609: {"name": "Chandelure", "types": ["ghost", "fire"], "generation": 5},
    610: {"name": "Axew", "types": ["dragon"], "generation": 5},
    611: {"name": "Fraxure", "types": ["dragon"], "generation": 5},
    612: {"name": "Haxorus", "types": ["dragon"], "generation": 5},
    613: {"name": "Cubchoo", "types": ["ice"], "generation": 5},
    614: {"name": "Beartic", "types": ["ice"], "generation": 5},
    615: {"name": "Cryogonal", "types": ["ice"], "generation": 5},
    616: {"name": "Shelmet", "types": ["bug"], "generation": 5},
    617: {"name": "Accelgor", "types": ["bug"], "generation": 5},
    618: {"name": "Stunfisk", "types": ["ground", "electric"], "generation": 5},
    619: {"name": "Mienfoo", "types": ["fighting"], "generation": 5},
    620: {"name": "Mienshao", "types": ["fighting"], "generation": 5},
    621: {"name": "Druddigon", "types": ["dragon"], "generation": 5},
    622: {"name": "Golett", "types": ["ground", "ghost"], "generation": 5},
    623: {"name": "Golurk", "types": ["ground", "ghost"], "generation": 5},
    624: {"name": "Pawniard", "types": ["dark", "steel"], "generation": 5},
    625: {"name": "Bisharp", "types": ["dark", "steel"], "generation": 5},
    626: {"name": "Bouffalant", "types": ["normal"], "generation": 5},
    627: {"name": "Rufflet", "types": ["normal", "flying"], "generation": 5},
    628: {"name": "Braviary", "types": ["normal", "flying"], "generation": 5},
    629: {"name": "Vullaby", "types": ["dark", "flying"], "generation": 5},
    630: {"name": "Mandibuzz", "types": ["dark", "flying"], "generation": 5},
    631: {"name": "Heatmor", "types": ["fire"], "generation": 5},
    632: {"name": "Durant", "types": ["bug", "steel"], "generation": 5},
    633: {"name": "Deino", "types": ["dark", "dragon"], "generation": 5},
    634: {"name": "Zweilous", "types": ["dark", "dragon"], "generation": 5},
    635: {"name": "Hydreigon", "types": ["dark", "dragon"], "generation": 5},
    636: {"name": "Larvesta", "types": ["bug", "fire"], "generation": 5},
    637: {"name": "Volcarona", "types": ["bug", "fire"], "generation": 5},
    638: {"name": "Cobalion", "types": ["steel", "fighting"], "generation": 5},
    639: {"name": "Terrakion", "types": ["rock", "fighting"], "generation": 5},
    640: {"name": "Virizion", "types": ["grass", "fighting"], "generation": 5},
    641: {"name": "Tornadus Incarnate", "types": ["flying"], "generation": 5},
    642: {"name": "Thundurus Incarnate", "types": ["electric", "flying"], "generation": 5},
    643: {"name": "Reshiram", "types": ["dragon", "fire"], "generation": 5},
    644: {"name": "Zekrom", "types": ["dragon", "electric"], "generation": 5},
    645: {"name": "Landorus Incarnate", "types": ["ground", "flying"], "generation": 5},
    646: {"name": "Kyurem", "types": ["dragon", "ice"], "generation": 5},
    647: {"name": "Keldeo Ordinary", "types": ["water", "fighting"], "generation": 5},
    648: {"name": "Meloetta Aria", "types": ["normal", "psychic"], "generation": 5},
    649: {"name": "Genesect", "types": ["bug", "steel"], "generation": 5},
    650: {"name": "Chespin", "types": ["grass"], "generation": 6},
    651: {"name": "Quilladin", "types": ["grass"], "generation": 6},
    652: {"name": "Chesnaught", "types": ["grass", "fighting"], "generation": 6},
    653: {"name": "Fennekin", "types": ["fire"], "generation": 6},
    654: {"name": "Braixen", "types": ["fire"], "generation": 6},
    655: {"name": "Delphox", "types": ["fire", "psychic"], "generation": 6},
    656: {"name": "Froakie", "types": ["water"], "generation": 6},
    657: {"name": "Frogadier", "types": ["water"], "generation": 6},
    658: {"name": "Greninja", "types": ["water", "dark"], "generation": 6},
    659: {"name": "Bunnelby", "types": ["normal"], "generation": 6},
    660: {"name": "Diggersby", "types": ["normal", "ground"], "generation": 6},
    661: {"name": "Fletchling", "types": ["normal", "flying"], "generation": 6},
    662: {"name": "Fletchinder", "types": ["fire", "flying"], "generation": 6},
    663: {"name": "Talonflame", "types": ["fire", "flying"], "generation": 6},
    664: {"name": "Scatterbug", "types": ["bug"], "generation": 6},
    665: {"name": "Spewpa", "types": ["bug"], "generation": 6},
    666: {"name": "Vivillon", "types": ["bug", "flying"], "generation": 6},
    667: {"name": "Litleo", "types": ["fire", "normal"], "generation": 6},
    668: {"name": "Pyroar", "types": ["fire", "normal"], "generation": 6},
    669: {"name": "Flabebe", "types": ["fairy"], "generation": 6},
    670: {"name": "Floette", "types": ["fairy"], "generation": 6},
    671: {"name": "Florges", "types": ["fairy"], "generation": 6},
    672: {"name": "Skiddo", "types": ["grass"], "generation": 6},
    673: {"name": "Gogoat", "types": ["grass"], "generation": 6},
    674: {"name": "Pancham", "types": ["fighting"], "generation": 6},
    675: {"name": "Pangoro", "types": ["fighting", "dark"], "generation": 6},
    676: {"name": "Furfrou", "types": ["normal"], "generation": 6},
    677: {"name": "Espurr", "types": ["psychic"], "generation": 6},
    678: {"name": "Meowstic Male", "types": ["psychic"], "generation": 6},
    679: {"name": "Honedge", "types": ["steel", "ghost"], "generation": 6},
    680: {"name": "Doublade", "types": ["steel", "ghost"], "generation": 6},
    681: {"name": "Aegislash Shield", "types": ["steel", "ghost"], "generation": 6},
    682: {"name": "Spritzee", "types": ["fairy"], "generation": 6},
    683: {"name": "Aromatisse", "types": ["fairy"], "generation": 6},
    684: {"name": "Swirlix", "types": ["fairy"], "generation": 6},
    685: {"name": "Slurpuff", "types": ["fairy"], "generation": 6},
    686: {"name": "Inkay", "types": ["dark", "psychic"], "generation": 6},
    687: {"name": "Malamar", "types": ["dark", "psychic"], "generation": 6},
    688: {"name": "Binacle", "types": ["rock", "water"], "generation": 6},
    689: {"name": "Barbaracle", "types": ["rock", "water"], "generation": 6},
    690: {"name": "Skrelp", "types": ["poison", "water"], "generation": 6},
    691: {"name": "Dragalge", "types": ["poison", "dragon"], "generation": 6},
    692: {"name": "Clauncher", "types": ["water"], "generation": 6},
    693: {"name": "Clawitzer", "types": ["water"], "generation": 6},
    694: {"name": "Helioptile", "types": ["electric", "normal"], "generation": 6},
    695: {"name": "Heliolisk", "types": ["electric", "normal"], "generation": 6},
    696: {"name": "Tyrunt", "types": ["rock", "dragon"], "generation": 6},
    697: {"name": "Tyrantrum", "types": ["rock", "dragon"], "generation": 6},
    698: {"name": "Amaura", "types": ["rock", "ice"], "generation": 6},
    699: {"name": "Aurorus", "types": ["rock", "ice"], "generation": 6},
    700: {"name": "Sylveon", "types": ["fairy"], "generation": 6},
    701: {"name": "Hawlucha", "types": ["fighting", "flying"], "generation": 6},
    702: {"name": "Dedenne", "types": ["electric", "fairy"], "generation": 6},
    703: {"name": "Carbink", "types": ["rock", "fairy"], "generation": 6},
    704: {"name": "Goomy", "types": ["dragon"], "generation": 6},
    705: {"name": "Sliggoo", "types": ["dragon"], "generation": 6},
    706: {"name": "Goodra", "types": ["dragon"], "generation": 6},
    707: {"name": "Klefki", "types": ["steel", "fairy"], "generation": 6},
    708: {"name": "Phantump", "types": ["ghost", "grass"], "generation": 6},
    709: {"name": "Trevenant", "types": ["ghost", "grass"], "generation": 6},
    710: {"name": "Pumpkaboo Average", "types": ["ghost", "grass"], "generation": 6},
    711: {"name": "Gourgeist Average", "types": ["ghost", "grass"], "generation": 6},
    712: {"name": "Bergmite", "types": ["ice"], "generation": 6},
    713: {"name": "Avalugg", "types": ["ice"], "generation": 6},
    714: {"name": "Noibat", "types": ["flying", "dragon"], "generation": 6},
    715: {"name": "Noivern", "types": ["flying", "dragon"], "generation": 6},
    716: {"name": "Xerneas", "types": ["fairy"], "generation": 6},
    717: {"name": "Yveltal", "types": ["dark", "flying"], "generation": 6},
    718: {"name": "Zygarde 50", "types": ["dragon", "ground"], "generation": 6},
    719: {"name": "Diancie", "types": ["rock", "fairy"], "generation": 6},
    720: {"name": "Hoopa", "types": ["psychic", "ghost"], "generation": 6},
    721: {"name": "Volcanion", "types": ["fire", "water"], "generation": 6},
    722: {"name": "Rowlet", "types": ["grass", "flying"], "generation": 7},
    723: {"name": "Dartrix", "types": ["grass", "flying"], "generation": 7},
    724: {"name": "Decidueye", "types": ["grass", "ghost"], "generation": 7},
    725: {"name": "Litten", "types": ["fire"], "generation": 7},
    726: {"name": "Torracat", "types": ["fire"], "generation": 7},
    727: {"name": "Incineroar", "types": ["fire", "dark"], "generation": 7},
    728: {"name": "Popplio", "types": ["water"], "generation": 7},
    729: {"name": "Brionne", "types": ["water"], "generation": 7},
    730: {"name": "Primarina", "types": ["water", "fairy"], "generation": 7},
    731: {"name": "Pikipek", "types": ["normal", "flying"], "generation": 7},
    732: {"name": "Trumbeak", "types": ["normal", "flying"], "generation": 7},
    733: {"name": "Toucannon", "types": ["normal", "flying"], "generation": 7},
    734: {"name": "Yungoos", "types": ["normal"], "generation": 7},
    735: {"name": "Gumshoos", "types": ["normal"], "generation": 7},
    736: {"name": "Grubbin", "types": ["bug"], "generation": 7},
    737: {"name": "Charjabug", "types": ["bug", "electric"], "generation": 7},
    738: {"name": "Vikavolt", "types": ["bug", "electric"], "generation": 7},
    739: {"name": "Crabrawler", "types": ["fighting"], "generation": 7},
    740: {"name": "Crabominable", "types": ["fighting", "ice"], "generation": 7},
    741: {"name": "Oricorio Baile", "types": ["fire", "flying"], "generation": 7},
    742: {"name": "Cutiefly", "types": ["bug", "fairy"], "generation": 7},
    743: {"name": "Ribombee", "types": ["bug", "fairy"], "generation": 7},
    744: {"name": "Rockruff", "types": ["rock"], "generation": 7},
    745: {"name": "Lycanroc Midday", "types": ["rock"], "generation": 7},
    746: {"name": "Wishiwashi Solo", "types": ["water"], "generation": 7},
    747: {"name": "Mareanie", "types": ["poison", "water"], "generation": 7},
    748: {"name": "Toxapex", "types": ["poison", "water"], "generation": 7},
    749: {"name": "Mudbray", "types": ["ground"], "generation": 7},
    750: {"name": "Mudsdale", "types": ["ground"], "generation": 7},
    751: {"name": "Dewpider", "types": ["water", "bug"], "generation": 7},
    752: {"name": "Araquanid", "types": ["water", "bug"], "generation": 7},
    753: {"name": "Fomantis", "types": ["grass"], "generation": 7},
    754: {"name": "Lurantis", "types": ["grass"], "generation": 7},
    755: {"name": "Morelull", "types": ["grass", "fairy"], "generation": 7},
    756: {"name": "Shiinotic", "types": ["grass", "fairy"], "generation": 7},
    757: {"name": "Salandit", "types": ["poison", "fire"], "generation": 7},
    758: {"name": "Salazzle", "types": ["poison", "fire"], "generation": 7},
    759: {"name": "Stufful", "types": ["normal", "fighting"], "generation": 7},
    760: {"name": "Bewear", "types": ["normal", "fighting"], "generation": 7},
    761: {"name": "Bounsweet", "types": ["grass"], "generation": 7},
    762: {"name": "Steenee", "types": ["grass"], "generation": 7},
    763: {"name": "Tsareena", "types": ["grass"], "generation": 7},
    764: {"name": "Comfey", "types": ["fairy"], "generation": 7},
    765: {"name": "Oranguru", "types": ["normal", "psychic"], "generation": 7},
    766: {"name": "Passimian", "types": ["fighting"], "generation": 7},
    767: {"name": "Wimpod", "types": ["bug", "water"], "generation": 7},
    768: {"name": "Golisopod", "types": ["bug", "water"], "generation": 7},
    769: {"name": "Sandygast", "types": ["ghost", "ground"], "generation": 7},
    770: {"name": "Palossand", "types": ["ghost", "ground"], "generation": 7},
    771: {"name": "Pyukumuku", "types": ["water"], "generation": 7},
    772: {"name": "Type Null", "types": ["normal"], "generation": 7},
    773: {"name": "Silvally", "types": ["normal"], "generation": 7},
    774: {"name": "Minior Red Meteor", "types": ["rock", "flying"], "generation": 7},
    775: {"name": "Komala", "types": ["normal"], "generation": 7},
    776: {"name": "Turtonator", "types": ["fire", "dragon"], "generation": 7},
    777: {"name": "Togedemaru", "types": ["electric", "steel"], "generation": 7},
    778: {"name": "Mimikyu Disguised", "types": ["ghost", "fairy"], "generation": 7},
    779: {"name": "Bruxish", "types": ["water", "psychic"], "generation": 7},
    780: {"name": "Drampa", "types": ["normal", "dragon"], "generation": 7},
    781: {"name": "Dhelmise", "types": ["ghost", "grass"], "generation": 7},
    782: {"name": "Jangmo O", "types": ["dragon"], "generation": 7},
    783: {"name": "Hakamo O", "types": ["dragon", "fighting"], "generation": 7},
    784: {"name": "Kommo O", "types": ["dragon", "fighting"], "generation": 7},
    785: {"name": "Tapu Koko", "types": ["electric", "fairy"], "generation": 7},
    786: {"name": "Tapu Lele", "types": ["psychic", "fairy"], "generation": 7},
    787: {"name": "Tapu Bulu", "types": ["grass", "fairy"], "generation": 7},
    788: {"name": "Tapu Fini", "types": ["water", "fairy"], "generation": 7},
    789: {"name": "Cosmog", "types": ["psychic"], "generation": 7},
    790: {"name": "Cosmoem", "types": ["psychic"], "generation": 7},
    791: {"name": "Solgaleo", "types": ["psychic", "steel"], "generation": 7},
    792: {"name": "Lunala", "types": ["psychic", "ghost"], "generation": 7},
    793: {"name": "Nihilego", "types": ["rock", "poison"], "generation": 7},
    794: {"name": "Buzzwole", "types": ["bug", "fighting"], "generation": 7},
    795: {"name": "Pheromosa", "types": ["bug", "fighting"], "generation": 7},
    796: {"name": "Xurkitree", "types": ["electric"], "generation": 7},
    797: {"name": "Celesteela", "types": ["steel", "flying"], "generation": 7},
    798: {"name": "Kartana", "types": ["grass", "steel"], "generation": 7},
    799: {"name": "Guzzlord", "types": ["dark", "dragon"], "generation": 7},
    800: {"name": "Necrozma", "types": ["psychic"], "generation": 7},
    801: {"name": "Magearna", "types": ["steel", "fairy"], "generation": 7},
    802: {"name": "Marshadow", "types": ["fighting", "ghost"], "generation": 7},
    803: {"name": "Poipole", "types": ["poison"], "generation": 7},
    804: {"name": "Naganadel", "types": ["poison", "dragon"], "generation": 7},
    805: {"name": "Stakataka", "types": ["rock", "steel"], "generation": 7},
    806: {"name": "Blacephalon", "types": ["fire", "ghost"], "generation": 7},
    807: {"name": "Zeraora", "types": ["electric"], "generation": 7},
    808: {"name": "Meltan", "types": ["steel"], "generation": 7},
    809: {"name": "Melmetal", "types": ["steel"], "generation": 7},
    810: {"name": "Grookey", "types": ["grass"], "generation": 8},
    811: {"name": "Thwackey", "types": ["grass"], "generation": 8},
    812: {"name": "Rillaboom", "types": ["grass"], "generation": 8},
    813: {"name": "Scorbunny", "types": ["fire"], "generation": 8},
    814: {"name": "Raboot", "types": ["fire"], "generation": 8},
    815: {"name": "Cinderace", "types": ["fire"], "generation": 8},
    816: {"name": "Sobble", "types": ["water"], "generation": 8},
    817: {"name": "Drizzile", "types": ["water"], "generation": 8},
    818: {"name": "Inteleon", "types": ["water"], "generation": 8},
    819: {"name": "Skwovet", "types": ["normal"], "generation": 8},
    820: {"name": "Greedent", "types": ["normal"], "generation": 8},
    821: {"name": "Rookidee", "types": ["flying"], "generation": 8},
    822: {"name": "Corvisquire", "types": ["flying"], "generation": 8},
    823: {"name": "Corviknight", "types": ["flying", "steel"], "generation": 8},
    824: {"name": "Blipbug", "types": ["bug"], "generation": 8},
    825: {"name": "Dottler", "types": ["bug", "psychic"], "generation": 8},
    826: {"name": "Orbeetle", "types": ["bug", "psychic"], "generation": 8},
    827: {"name": "Nickit", "types": ["dark"], "generation": 8},
    828: {"name": "Thievul", "types": ["dark"], "generation": 8},
    829: {"name": "Gossifleur", "types": ["grass"], "generation": 8},
    830: {"name": "Eldegoss", "types": ["grass"], "generation": 8},
    831: {"name": "Wooloo", "types": ["normal"], "generation": 8},
    832: {"name": "Dubwool", "types": ["normal"], "generation": 8},
    833: {"name": "Chewtle", "types": ["water"], "generation": 8},
    834: {"name": "Drednaw", "types": ["water", "rock"], "generation": 8},
    835: {"name": "Yamper", "types": ["electric"], "generation": 8},
    836: {"name": "Boltund", "types": ["electric"], "generation": 8},
    837: {"name": "Rolycoly", "types": ["rock"], "generation": 8},
    838: {"name": "Carkol", "types": ["rock", "fire"], "generation": 8},
    839: {"name": "Coalossal", "types": ["rock", "fire"], "generation": 8},
    840: {"name": "Applin", "types": ["grass", "dragon"], "generation": 8},
    841: {"name": "Flapple", "types": ["grass", "dragon"], "generation": 8},
    842: {"name": "Appletun", "types": ["grass", "dragon"], "generation": 8},
    843: {"name": "Silicobra", "types": ["ground"], "generation": 8},
    844: {"name": "Sandaconda", "types": ["ground"], "generation": 8},
    845: {"name": "Cramorant", "types": ["flying", "water"], "generation": 8},
    846: {"name": "Arrokuda", "types": ["water"], "generation": 8},
    847: {"name": "Barraskewda", "types": ["water"], "generation": 8},
    848: {"name": "Toxel", "types": ["electric", "poison"], "generation": 8},
    849: {"name": "Toxtricity Amped", "types": ["electric", "poison"], "generation": 8},
    850: {"name": "Sizzlipede", "types": ["fire", "bug"], "generation": 8},
    851: {"name": "Centiskorch", "types": ["fire", "bug"], "generation": 8},
    852: {"name": "Clobbopus", "types": ["fighting"], "generation": 8},
    853: {"name": "Grapploct", "types": ["fighting"], "generation": 8},
    854: {"name": "Sinistea", "types": ["ghost"], "generation": 8},
    855: {"name": "Polteageist", "types": ["ghost"], "generation": 8},
    856: {"name": "Hatenna", "types": ["psychic"], "generation": 8},
    857: {"name": "Hattrem", "types": ["psychic"], "generation": 8},
    858: {"name": "Hatterene", "types": ["psychic", "fairy"], "generation": 8},
    859: {"name": "Impidimp", "types": ["dark", "fairy"], "generation": 8},
    860: {"name": "Morgrem", "types": ["dark", "fairy"], "generation": 8},
    861: {"name": "Grimmsnarl", "types": ["dark", "fairy"], "generation": 8},
    862: {"name": "Obstagoon", "types": ["dark", "normal"], "generation": 8},
    863: {"name": "Perrserker", "types": ["steel"], "generation": 8},
    864: {"name": "Cursola", "types": ["ghost"], "generation": 8},
    865: {"name": "Sirfetchd", "types": ["fighting"], "generation": 8},
    866: {"name": "Mr Rime", "types": ["ice", "psychic"], "generation": 8},
    867: {"name": "Runerigus", "types": ["ground", "ghost"], "generation": 8},
    868: {"name": "Milcery", "types": ["fairy"], "generation": 8},
    869: {"name": "Alcremie", "types": ["fairy"], "generation": 8},
    870: {"name": "Falinks", "types": ["fighting"], "generation": 8},
    871: {"name": "Pincurchin", "types": ["electric"], "generation": 8},
    872: {"name": "Snom", "types": ["ice", "bug"], "generation": 8},
    873: {"name": "Frosmoth", "types": ["ice", "bug"], "generation": 8},
    874: {"name": "Stonjourner", "types": ["rock"], "generation": 8},
    875: {"name": "Eiscue Ice", "types": ["ice"], "generation": 8},
    876: {"name": "Indeedee Male", "types": ["psychic", "normal"], "generation": 8},
    877: {"name": "Morpeko Full Belly", "types": ["electric", "dark"], "generation": 8},
    878: {"name": "Cufant", "types": ["steel"], "generation": 8},
    879: {"name": "Copperajah", "types": ["steel"], "generation": 8},
    880: {"name": "Dracozolt", "types": ["electric", "dragon"], "generation": 8},
    881: {"name": "Arctozolt", "types": ["electric", "ice"], "generation": 8},
    882: {"name": "Dracovish", "types": ["water", "dragon"], "generation": 8},
    883: {"name": "Arctovish", "types": ["water", "ice"], "generation": 8},
    884: {"name": "Duraludon", "types": ["steel", "dragon"], "generation": 8},
    885: {"name": "Dreepy", "types": ["dragon", "ghost"], "generation": 8},
    886: {"name": "Drakloak", "types": ["dragon", "ghost"], "generation": 8},
    887: {"name": "Dragapult", "types": ["dragon", "ghost"], "generation": 8},
    888: {"name": "Zacian", "types": ["fairy"], "generation": 8},
    889: {"name": "Zamazenta", "types": ["fighting"], "generation": 8},
    890: {"name": "Eternatus", "types": ["poison", "dragon"], "generation": 8},
    891: {"name": "Kubfu", "types": ["fighting"], "generation": 8},
    892: {"name": "Urshifu Single Strike", "types": ["fighting", "dark"], "generation": 8},
    893: {"name": "Zarude", "types": ["dark", "grass"], "generation": 8},
    894: {"name": "Regieleki", "types": ["electric"], "generation": 8},
    895: {"name": "Regidrago", "types": ["dragon"], "generation": 8},
    896: {"name": "Glastrier", "types": ["ice"], "generation": 8},
    897: {"name": "Spectrier", "types": ["ghost"], "generation": 8},
    898: {"name": "Calyrex", "types": ["psychic", "grass"], "generation": 8},
    899: {"name": "Wyrdeer", "types": ["normal", "psychic"], "generation": 8},
    900: {"name": "Kleavor", "types": ["bug", "rock"], "generation": 8},
    901: {"name": "Ursaluna", "types": ["ground", "normal"], "generation": 8},
    902: {"name": "Basculegion Male", "types": ["water", "ghost"], "generation": 8},
    903: {"name": "Sneasler", "types": ["fighting", "poison"], "generation": 8},
    904: {"name": "Overqwil", "types": ["dark", "poison"], "generation": 8},
    905: {"name": "Enamorus Incarnate", "types": ["fairy", "flying"], "generation": 8},
    906: {"name": "Sprigatito", "types": ["grass"], "generation": 9},
    907: {"name": "Floragato", "types": ["grass"], "generation": 9},
    908: {"name": "Meowscarada", "types": ["grass", "dark"], "generation": 9},
    909: {"name": "Fuecoco", "types": ["fire"], "generation": 9},
    910: {"name": "Crocalor", "types": ["fire"], "generation": 9},
    911: {"name": "Skeledirge", "types": ["fire", "ghost"], "generation": 9},
    912: {"name": "Quaxly", "types": ["water"], "generation": 9},
    913: {"name": "Quaxwell", "types": ["water"], "generation": 9},
    914: {"name": "Quaquaval", "types": ["water", "fighting"], "generation": 9},
    915: {"name": "Lechonk", "types": ["normal"], "generation": 9},
    916: {"name": "Oinkologne Male", "types": ["normal"], "generation": 9},
    917: {"name": "Tarountula", "types": ["bug"], "generation": 9},
    918: {"name": "Spidops", "types": ["bug"], "generation": 9},
    919: {"name": "Nymble", "types": ["bug"], "generation": 9},
    920: {"name": "Lokix", "types": ["bug", "dark"], "generation": 9},
    921: {"name": "Pawmi", "types": ["electric"], "generation": 9},
    922: {"name": "Pawmo", "types": ["electric", "fighting"], "generation": 9},
    923: {"name": "Pawmot", "types": ["electric", "fighting"], "generation": 9},
    924: {"name": "Tandemaus", "types": ["normal"], "generation": 9},
    925: {"name": "Maushold Family Of Four", "types": ["normal"], "generation": 9},
    926: {"name": "Fidough", "types": ["fairy"], "generation": 9},
    927: {"name": "Dachsbun", "types": ["fairy"], "generation": 9},
    928: {"name": "Smoliv", "types": ["grass", "normal"], "generation": 9},
    929: {"name": "Dolliv", "types": ["grass", "normal"], "generation": 9},
    930: {"name": "Arboliva", "types": ["grass", "normal"], "generation": 9},
    931: {"name": "Squawkabilly Green Plumage", "types": ["normal", "flying"], "generation": 9},
    932: {"name": "Nacli", "types": ["rock"], "generation": 9},
    933: {"name": "Naclstack", "types": ["rock"], "generation": 9},
    934: {"name": "Garganacl", "types": ["rock"], "generation": 9},
    935: {"name": "Charcadet", "types": ["fire"], "generation": 9},
    936: {"name": "Armarouge", "types": ["fire", "psychic"], "generation": 9},
    937: {"name": "Ceruledge", "types": ["fire", "ghost"], "generation": 9},
    938: {"name": "Tadbulb", "types": ["electric"], "generation": 9},
    939: {"name": "Bellibolt", "types": ["electric"], "generation": 9},
    940: {"name": "Wattrel", "types": ["electric", "flying"], "generation": 9},
    941: {"name": "Kilowattrel", "types": ["electric", "flying"], "generation": 9},
    942: {"name": "Maschiff", "types": ["dark"], "generation": 9},
    943: {"name": "Mabosstiff", "types": ["dark"], "generation": 9},
    944: {"name": "Shroodle", "types": ["poison", "normal"], "generation": 9},
    945: {"name": "Grafaiai", "types": ["poison", "normal"], "generation": 9},
    946: {"name": "Bramblin", "types": ["grass", "ghost"], "generation": 9},
    947: {"name": "Brambleghast", "types": ["grass", "ghost"], "generation": 9},
    948: {"name": "Toedscool", "types": ["ground", "grass"], "generation": 9},
    949: {"name": "Toedscruel", "types": ["ground", "grass"], "generation": 9},
    950: {"name": "Klawf", "types": ["rock"], "generation": 9},
    951: {"name": "Capsakid", "types": ["grass"], "generation": 9},
    952: {"name": "Scovillain", "types": ["grass", "fire"], "generation": 9},
    953: {"name": "Rellor", "types": ["bug"], "generation": 9},
    954: {"name": "Rabsca", "types": ["bug", "psychic"], "generation": 9},
    955: {"name": "Flittle", "types": ["psychic"], "generation": 9},
    956: {"name": "Espathra", "types": ["psychic"], "generation": 9},
    957: {"name": "Tinkatink", "types": ["fairy", "steel"], "generation": 9},
    958: {"name": "Tinkatuff", "types": ["fairy", "steel"], "generation": 9},
    959: {"name": "Tinkaton", "types": ["fairy", "steel"], "generation": 9},
    960: {"name": "Wiglett", "types": ["water"], "generation": 9},
    961: {"name": "Wugtrio", "types": ["water"], "generation": 9},
    962: {"name": "Bombirdier", "types": ["flying", "dark"], "generation": 9},
    963: {"name": "Finizen", "types": ["water"], "generation": 9},
    964: {"name": "Palafin Zero", "types": ["water"], "generation": 9},
    965: {"name": "Varoom", "types": ["steel", "poison"], "generation": 9},
    966: {"name": "Revavroom", "types": ["steel", "poison"], "generation": 9},
    967: {"name": "Cyclizar", "types": ["dragon", "normal"], "generation": 9},
    968: {"name": "Orthworm", "types": ["steel"], "generation": 9},
    969: {"name": "Glimmet", "types": ["rock", "poison"], "generation": 9},
    970: {"name": "Glimmora", "types": ["rock", "poison"], "generation": 9},
    971: {"name": "Greavard", "types": ["ghost"], "generation": 9},
    972: {"name": "Houndstone", "types": ["ghost"], "generation": 9},
    973: {"name": "Flamigo", "types": ["flying", "fighting"], "generation": 9},
    974: {"name": "Cetoddle", "types": ["ice"], "generation": 9},
    975: {"name": "Cetitan", "types": ["ice"], "generation": 9},
    976: {"name": "Veluza", "types": ["water", "psychic"], "generation": 9},
    977: {"name": "Dondozo", "types": ["water"], "generation": 9},
    978: {"name": "Tatsugiri Curly", "types": ["dragon", "water"], "generation": 9},
    979: {"name": "Annihilape", "types": ["fighting", "ghost"], "generation": 9},
    980: {"name": "Clodsire", "types": ["poison", "ground"], "generation": 9},
    981: {"name": "Farigiraf", "types": ["normal", "psychic"], "generation": 9},
    982: {"name": "Dudunsparce Two Segment", "types": ["normal"], "generation": 9},
    983: {"name": "Kingambit", "types": ["dark", "steel"], "generation": 9},
    984: {"name": "Great Tusk", "types": ["ground", "fighting"], "generation": 9},
    985: {"name": "Scream Tail", "types": ["fairy", "psychic"], "generation": 9},
    986: {"name": "Brute Bonnet", "types": ["grass", "dark"], "generation": 9},
    987: {"name": "Flutter Mane", "types": ["ghost", "fairy"], "generation": 9},
    988: {"name": "Slither Wing", "types": ["bug", "fighting"], "generation": 9},
    989: {"name": "Sandy Shocks", "types": ["electric", "ground"], "generation": 9},
    990: {"name": "Iron Treads", "types": ["ground", "steel"], "generation": 9},
    991: {"name": "Iron Bundle", "types": ["ice", "water"], "generation": 9},
    992: {"name": "Iron Hands", "types": ["fighting", "electric"], "generation": 9},
    993: {"name": "Iron Jugulis", "types": ["dark", "flying"], "generation": 9},
    994: {"name": "Iron Moth", "types": ["fire", "poison"], "generation": 9},
    995: {"name": "Iron Thorns", "types": ["rock", "electric"], "generation": 9},
    996: {"name": "Frigibax", "types": ["dragon", "ice"], "generation": 9},
    997: {"name": "Arctibax", "types": ["dragon", "ice"], "generation": 9},
    998: {"name": "Baxcalibur", "types": ["dragon", "ice"], "generation": 9},
    999: {"name": "Gimmighoul", "types": ["ghost"], "generation": 9},
    1000: {"name": "Gholdengo", "types": ["steel", "ghost"], "generation": 9},
    1001: {"name": "Wo Chien", "types": ["dark", "grass"], "generation": 9},
    1002: {"name": "Chien Pao", "types": ["dark", "ice"], "generation": 9},
    1003: {"name": "Ting Lu", "types": ["dark", "ground"], "generation": 9},
    1004: {"name": "Chi Yu", "types": ["dark", "fire"], "generation": 9},
    1005: {"name": "Roaring Moon", "types": ["dragon", "dark"], "generation": 9},
    1006: {"name": "Iron Valiant", "types": ["fairy", "fighting"], "generation": 9},
    1007: {"name": "Koraidon", "types": ["fighting", "dragon"], "generation": 9},
    1008: {"name": "Miraidon", "types": ["electric", "dragon"], "generation": 9},
    1009: {"name": "Walking Wake", "types": ["water", "dragon"], "generation": 9},
    1010: {"name": "Iron Leaves", "types": ["grass", "psychic"], "generation": 9},
    1011: {"name": "Dipplin", "types": ["grass", "dragon"], "generation": 9},
    1012: {"name": "Poltchageist", "types": ["grass", "ghost"], "generation": 9},
    1013: {"name": "Sinistcha", "types": ["grass", "ghost"], "generation": 9},
    1014: {"name": "Okidogi", "types": ["poison", "fighting"], "generation": 9},
    1015: {"name": "Munkidori", "types": ["poison", "psychic"], "generation": 9},
    1016: {"name": "Fezandipiti", "types": ["poison", "fairy"], "generation": 9},
    1017: {"name": "Ogerpon", "types": ["grass"], "generation": 9},
    1018: {"name": "Archaludon", "types": ["steel", "dragon"], "generation": 9},
    1019: {"name": "Hydrapple", "types": ["grass", "dragon"], "generation": 9},
    1020: {"name": "Gouging Fire", "types": ["fire", "dragon"], "generation": 9},
    1021: {"name": "Raging Bolt", "types": ["electric", "dragon"], "generation": 9},
    1022: {"name": "Iron Boulder", "types": ["rock", "psychic"], "generation": 9},
    1023: {"name": "Iron Crown", "types": ["steel", "psychic"], "generation": 9},
    1024: {"name": "Terapagos", "types": ["normal"], "generation": 9},
    1025: {"name": "Pecharunt", "types": ["poison", "ghost"], "generation": 9},
}

def get_pokemon_info(pokemon_id):
    """Get Pokemon information by ID"""
    return POKEMON_DATA.get(pokemon_id)

def get_pokemon_types(pokemon_id):
    """Get Pokemon types by ID"""
    pokemon = POKEMON_DATA.get(pokemon_id)
    return pokemon["types"] if pokemon else []

def get_pokemon_generation(pokemon_id):
    """Get Pokemon generation by ID"""
    pokemon = POKEMON_DATA.get(pokemon_id)
    return pokemon["generation"] if pokemon else 1

# Statistics:
# Total Pokemon: 1025
# Generation breakdown:
# Generation 1: 151 Pokemon
# Generation 2: 100 Pokemon
# Generation 3: 135 Pokemon
# Generation 4: 107 Pokemon
# Generation 5: 156 Pokemon
# Generation 6: 72 Pokemon
# Generation 7: 88 Pokemon
# Generation 8: 96 Pokemon
# Generation 9: 120 Pokemon
